### ISSUE TITLE
Data fetch problem

### ISSUE THREAD

**Issue by 0JIEUN0** [WIT-Projects/RTiccle-App#29]
문제 상황: 필요한 데이터를 각 컴포넌트가 '독립적으로 가져옵니다.

데이터를 어떻게 하면 효율적으로 가져올 수 있을지,
'변경된' 데이터를 어떻게 화면에 바로 반영시킬지에 대한 수정이 필요합니다.

**Comment by 0JIEUN0** [comment]
관련 논의 내용:
- https://github.com/WIT-Projects/RTiccle-App/pull/24#discussion_r777271683
- https://github.com/WIT-Projects/RTiccle-App/pull/27#discussion_r779449725

**Comment by 0JIEUN0** [comment]
접근 1. 지금처럼, 필요할 때마다 데이터를 가져오자
    - 장점: 동기화를 신경쓸 필요가 없다.
    - 단점: 서버 요청이 필요 이상으로 발생
접근 2. 로컬 DB 를 두자
    - 장점: 서버 요청이 현저히 줄어든다.
    - 단점: 데이터가 많아질수록 앱이 무거워지고, 동기화 문제가 발생할 수 있다. + 보안 문제
접근 3. '자주 변경되는’ 데이터는 미리 받아와서 캐싱해서 사용하고, 나머지는 필요할 때마다 서버 요청을 수행한다.
    - 장점: 캐싱할 데이터를 잘 정의할수록 1보다 서버 요청이 줄어들면서 이 데이터의 동기화만 신경쓰면 된다.
    - 단점: 동기화 문제

에서 접근 3을 선택, (사유: 자주 사용하는 정보가 적음. 접근 방법 3가지 중에 가장 우리의 서비스에 합리적이라고 판단)
캐싱하는 데이터는 `useContext` 로 관리하여 데이터가 언제 '수정되었는지’ 를 함께 관리하고자 하는 방안을 세웠습니다.

즉, 다음의 정보를 재사용합니다.
- 전체 `group list`
- 사용자가 `GroupDetail` 에서 조회하는 그룹의 `ticcle list` (즉, 한 그룹의 ticcle 내용)

또한, view(화면) 에서는 데이터를 관리하는 상세 내용을 blackbox 처럼 생각하고 작동할 수 있도록,
view 와 데이터 로직을 분리하기 위해 `model` 에서 데이터를 처리하는 모든 로직을 관리하는 구조로 변경하였습니다.
따라서, view 에서는 더이상 `service` 가 아닌 `model` 을 사용하면 됩니다.

관련 commit: 00dfdd5, 463921b, 97f971d, 68694e6

**Comment by 0JIEUN0** [comment]
위의 방법을 사용하였는데, 다음의 2가지 문제가 발생했습니다.
- RN 에서 hook 은 함수 컴포넌트에서만 사용 가능 -> 결국 로컬 데이터를 변경하는 것은 view 에서 해줘야...
- 큰 데이터의 변경을 React 가 추적 (context 이기 때문) -> 과부화. 오류 발생 가능성이 높아짐


따라서, 위의 구조를 좀 변경하여 다음의 방법을 적용했습니다.
- 위의 구조의 재사용하는 정보는 동일합니다.
- 단, '데이터의 변경'을 추적하기 위해 재사용 정보를 context 로 통째로 관리한 것을, 재사용 정보가 변경되면 notify 해주는 형태로 변경했습니다. (notify 해주는 것은 context 를 사용. 해당 데이터를 쓰는 모든 컴포넌트가 전달받아야 하므로)
- 따라서 화면에서는 '화면 변경 여부'에 따라서 캐싱된 데이터를 다시 가져오는 방식으로 작동합니다.
- 또한, 화면에서 재사용 정보를 변경한 경우(create/update/delete...), 변경 내용을 관리하는 context 를 업데이트해주어 notify 를 해야 합니다.


결과적으로, 변경되는 데이터를 잘 잡아내어 화면에 반영하는 것을 확인했습니다.
(Group 에 대해서. Ticcle 은 아직 화면 쪽 로직이 정비가 안된 것 같아서 테스트하지는 못했습니다.)

관련 commit: 7ce553d, 77b3471, 7b8a4b7

이후 추가 이슈가 발생하지 않는다면 이 구조로 확정하고 이슈를 닫겠습니다.

**Comment by bella0413** [comment]
context로 관리하는 데이터의 크기가 현저히 줄어서 변경된 구조가 더 좋을 것 같습니다. 고민이 많으셨을텐데 너무 수고하셨어요👍👍

**Comment by 0JIEUN0** [comment]
#36 

까지 수정하여 현재 Group 쪽은 잘 작동하는 것으로 보입니다. 
그에 따라 이 issue 는 해결된 것으로 간주, close 하겠습니다!
