### ISSUE TITLE
Full text search problem

### ISSUE THREAD

**Issue by 0JIEUN0** [WIT-Projects/RTiccle-App#31]
현재 RTiccle 서비스는 Ticcle `title` 검색 혹은 `tag` 검색이 가능합니다.
그런데, firebase 에서는 full text 검색을 지원하지 않습니다.
- https://firebase.google.com/docs/firestore/solutions/search

이에 따라, 저희에겐 다음의 선택지가 있다고 볼 수 있습니다.
1. `title` 검색 기능 없애기
2. 다른 검색 제공업체(Elastic, Algolia 등)를 사용
  - firebase extensions 를 사용
  - 직접 연결
  - 비용 발생
3. 그냥 내부에서 다 받아와서 검사한다... 

어떻게 할지 논의가 필요합니다.

**Comment by never-better** [comment]
1. (3순위) 우선은 메모앱인데 메모 제목으로 못 찾는건 팥 없는 붕어빵이 되는 것 같아요
2. (1순위) Typesense가 open source라 우선 순위로 가져가고, 정 안되면 요금을 조금 지불해서라도....
3. (2순위) 단점이 많긴 하지만 안되면 요금을 낼 수 없다면 이렇게라도 해야죠....

**Comment by 0JIEUN0** [comment]
4. 티끌 개수가 100개이니, 티끌 `title`만 따로 저장해두고 자체 검색

**Comment by 0JIEUN0** [comment]
이번 주 동안 Algolia 를 cloud functions 로 연결하려고 노력하였으나 저희 firebase 구조 상 어려움이 존재해서 아직 진행중입니다.
더 시도해보고 가능하다면 Algolia 를 연결해서 검색하는 방법을 사용하고, 아니면 Algolia 도 결국 index 를 만들어서 관리하는 것이므로 저희 firestore 에 indexing 을 위한 document 같은 것을 두고 관리하는 것도 고려중입니다!

**Comment by 0JIEUN0** [comment]
최종 결정: `Algolia` 와 Firebase 를 연결해서 검색을 지원합니다.
- 관련 commit: f977608
- 관련 Cloud Functions: https://github.com/WIT-Projects/RTiccle-Functions
