### ISSUE TITLE
컴포넌트 재활용: TextInput

### ISSUE THREAD

**Issue by 0JIEUN0** [WIT-Projects/RTiccle-App#4]
TextInput 을 재활용하는 방향으로 구현하는 것 논의하고 수정해야 합니다.

_Originally posted by @0JIEUN0 in https://github.com/WIT-Projects/RTiccle-App/pull/2#discussion_r749235186_

**Comment by 0JIEUN0** [comment]
공통 TextInput 작성: https://github.com/WIT-Projects/RTiccle-App/pull/9#issue-1065798905
관련 논의 사항: https://github.com/WIT-Projects/RTiccle-App/pull/9#discussion_r758266995

**Comment by bella0413** [comment]
common 폴더에서 공통 컴포넌트를 따로 관리하기로 결정
