### ISSUE TITLE
앱 내에서 사용하는 Icon 정리

### ISSUE THREAD

**Issue by 0JIEUN0** [WIT-Projects/RTiccle-App#5]
외부 라이브러리 말고 앱 내에서 사용하는 Icon 에 대해 이미지를 두고 사용하기로 결정했습니다.
이에 따라 각 아이콘 이미지를 모듈화하여 사용할 필요가 있습니다.

_Originally posted by @0JIEUN0 in https://github.com/WIT-Projects/RTiccle-App/pull/3#r749325730_

**Comment by 0JIEUN0** [comment]
#3 02e10ac 에서 사용한 방식이 아니라 #2 5e9de66 에서 사용한 방식을 쓰되, 따로 컴포넌트화하여 가져다 쓰기 편하도록 해야 한다.

**Comment by bella0413** [comment]
RN 특성 상 컴포넌트의 재사용도 빈번하기 때문에 이미지의 경로와 컴포넌트 경로를 모두 고려하여
src 폴더를 root로 지정하기로 결정. 이미지, 컴포넌트 모두 절대경로로 접근하기로 함.

**Comment by 0JIEUN0** [comment]
참고 https://github.com/WIT-Projects/RTiccle-App/pull/9#discussion_r758286213
